### ISSUE TITLE
p-values from modeling ratios of counts?

### ISSUE THREAD

**Issue by snaqvi1990** [azhu513/apeglm#1]
Hello,

Apologies if this is the wrong place to ask this question, but I have used apeglm to model allelic imbalance across multiple replicates, similar to what is done in http://bioconductor.org/packages/release/bioc/vignettes/apeglm/inst/doc/apeglm.html#modeling_ratios_of_counts. It is working fine, but I was wondering if it is possible to derive traditional p-values in addition to the fsr/s-values that apeglm typically returns. I know in the vignette the s-values were compared to padj values from DESeq2, but this was for a typical DE setting whereas I am using a beta-binomial so that wouldn't apply.

Thanks in advance,
Sahin

**Comment by mikelove** [comment]
We don't have traditional p-values for `apeglm`, so you should use the s-values as proposed by Stephens (2016) as giving a bound on the false sign rate (FSR), and I think the same logic applies at to the DE example.
