### ISSUE TITLE
Missing values in allele-specific counts

### ISSUE THREAD

**Issue by leqi0001** [azhu513/apeglm#3]
Hi,

Thanks for developing the apeglm package! I've obtained allele-specific counts from around 50 samples using genotyping information. Since each sample has slightly different variants, only reads at heterozygous sites passing certain depth cutoff/base quality are counted. As a result, many values are missing in the final count matrix. This seems to be a problem for apeglm, which doesn't allow missing values (error message below). Is there a way to get around this with apeglm? It might make sense to fill up the missing values when the other allele for a certain gene is non-zero, but not when both counts are missing due to homozygosity or low coverage in certain samples. 

Error message using example data in your vignette but removing 1 or 2 values. 
fit.mle <- apeglm(Y=ase.cts, x=x, log.lik=NULL, param=param,
+                       no.shrink=TRUE, log.link=FALSE, method="betabinCR")
Error in seq_len(sum(nonzero)) : 
  argument must be coercible to non-negative integer

Le

**Comment by mikelove** [comment]
You can set the weight to 0 and then supply the count as 1/1 (or anything).

(replying from phone)
