### ISSUE TITLE
optimHess error

### ISSUE THREAD

**Issue by andrewjkwok** [azhu513/apeglm#6]
Hi,

I'm running into one of the optimHess errors:
```
Error in optimHess(par = init, fn = nbinomFn, gr = nbinomGr, x = x, y = y,  : 
  non-finite value supplied by optim
```
which seems to have been fixed for the latest version of apeglm #4. However, I have version 1.20.0 installed for apeglm which seems to already be the latest version for Bioconductor 3.16. I was wondering whether there might be any backward support for my version of apeglm or is it a must that I upgrade my bioconductor for this? Many thanks in advance.

**Comment by mikelove** [comment]
Sorry, Bioc only supports current and devel versions, we can't provide backward support (due to the scope of work that would entail)

**Comment by andrewjkwok** [comment]
Got it, thanks Mike!
